# Generated by Django 4.0 on 2022-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('thum_url', models.CharField(blank=True, max_length=300, null=True)),
                ('y', models.CharField(blank=True, max_length=15, null=True)),
                ('x', models.CharField(blank=True, max_length=15, null=True)),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cafe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CafeTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cafe_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('thum_url', models.CharField(blank=True, max_length=400, null=True)),
                ('y', models.CharField(blank=True, max_length=15, null=True)),
                ('x', models.CharField(blank=True, max_length=15, null=True)),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'res_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('numofrooms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stay',
                'managed': False,
            },
        ),
    ]
