# Generated by Django 4.0 on 2022-01-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeKwrd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cafe_kwrd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResKwrd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'res_kwrd',
                'managed': False,
            },
        ),
    ]
